name = "FantastiCreate Dev"
author = "akai_hana"
version = "8.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62ff26a0d7ff769cddd7136ca5d0df24d7ed498a55ed81b1b2904e10171affa8"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
