noWander = true
fairBreeds = true
portalPatch = true
rubberBand = true
breakSpeed = true
stepHeight = true
horseHeadAngleOffset = 45
jeb_Horses = true

[pitchFade]
enabled = true
startAngle = 90
endAngle = 50
maxTransparency = 97
