enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = true
powderSnowCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
edenring = true
angelblockrenewed = true
everycomp = true
bountiful = true
farmersdelight = true
create_new_age = true
species = true
wondrouswilds = true
betternether = true
brewery = true
galosphere = true
friendsandfoes = true
ecologics = true
twigs = true
visualoverhaul = true
sprout = true
dramaticdoors = true
comforts = true
duckling = true
yigd = true
byg = true
campchair = true
elitia = true
additionaladditions = true
sleep_tight = true
railways = true
the_bumblezone = true
handcrafted = true
dehydration = true
ftbquests = true
frostiful = true
snowrealmagic = true
botanypotstiers = true
additions = true
charm = true
naturalist = true
disenchanter = true
creategoggles = true
customportalapi = true
hybrid-aquatic = true
casualness_delight = true
supplementaries = true
magnumtorch = true
promenade = true
deeperdarker = true
endrem = true
culturaldelights = true
create = true
echochest = true
windchimes = true
rottencreatures = true
createoreexcavation = true
jmc = true
woof = true
davespotioneering = true
just_end_anchor = true
farmersrespite = true
minecraft = true
nutritious_feast = true
morebeautifultorches = true
travelersbackpack = true
twilightforest = true
dragonloot = true
adventurez = true
creeperoverhaul = true
tradingpost = true
pyrotastic = true
paradise_lost = true
bushierflowers = true
puddles = true
carpeted = true
expandeddelight = true
toms_storage = true
delightfulcreators = true
excessive_building = true
universal_ores = true
cinderscapes = true
barteringstation = true
overweight_farming = true
oxidized = true
bettermod = true
betterend = true
respitecreators = true
connectedglass = true
oceansdelight = true
bambooeverything = true
variantcraftingtables = true
another_furniture = true
frozenup = true
bygonenether = true
copperhopper = true
automobility = true
lightestlamp = true
createutilities = true
snowyspirit = true
farmingforblockheads = true
nethersdelight = true
create_enchantment_industry = true
fastpaintings = true
botanypots = true
milk = true
enchantsmith = true
advancementframes = true
earthtojavamobs = true
advancednetherite = true
creatures_from_the_snow = true
sod = true
graveyard = true
deepslatecutting = true
more_slabs_stairs_and_walls = true
ubesdelight = true
minerally = true
convenientdecor = true
winterly = true
quartzelv = true
clutter = true
terrestria = true
biomemakeover = true
geodes = true
spirit = true
create_deco_casing = true
goodall = true
craftingbench = true
better_withered_mobs = true
plushies = true
architects_palette = true
angling = true
fwaystones = true
lootr = true
compress_it = true
regions_unexplored = true
bosses_of_mass_destruction = true
beautify = true
extshape = true
immersive_weathering = true
decorative_blocks = true
voidz = true
miningutility = true
villagersplus = true
netherdepthsupgrade = true
vinery = true
gofish = true
blockus = true
meadow = true
betterperf = true
rechiseled = true
grapplemod = true
