enabled = true
timeoutMs = 60000
# Must be between 1000 and 60000.

[Trigger]
whenMinimized = true
# Tape stops when the game is minimized.

whenLostFocus = true
# Tape stops when the game loses focus.

afterGUITimeout = true
# Tape stops when the game is in a GUI screen(inventory, pause menu, etc.) and reaches the timeout specified above.

afterGameTimeout = true
# Tape stops when the game is not in a GUI screen and reaches the timeout specified above.

[Debug]
debug = false
# Prints debug messages to the console.

[Visual]
panorama = false
# Renders the panorama background while tape stopped.